dropbox-token: y7eS5BQXTJAAAAAAABGR-7rN3EC1ar0qe2SKS6B1bzcbajY_s402j0ekSTRB6tIl

# TeleNav LDAP authentication
ldap:
  uri: ldap://hq-tndc-03.telenav.com:3268
  search_base_dn: DC=telenav,DC=com
  ro_account: CN=tracker,CN=users,DC=telenav,DC=com
  ro_password: trackerpna

# Forumsys testing authentication.
ldap-test:
  uri: ldap://ldap.forumsys.com:389
  search_base_dn: dc=example,dc=com
  ro_account: cn=read-only-admin,dc=example,dc=com
  ro_password: password

# Authorized users
acl:
  - newton
  - jamiel
  - garyn
  - chrisk
  - hectorv